Repository cozy/cozy-ui, pull requests merged in 2018-06, with the labels that each got.

#525 feat: add global utility classes
  .stylintrc
  react/MidEllipsis/index.jsx
  react/MidEllipsis/styles.styl
  react/Text/index.jsx
  react/Text/styles.styl
  stylus/utilities/display.styl
  stylus/utilities/spaces.styl
  stylus/utilities/text.styl
Labels: enhancement

#529 fix: global styles are compiled only when used with CSS-modules
  stylus/cozy-ui/build.styl
  stylus/cozy-ui/index.styl
  stylus/tools/mixins.styl
  stylus/utilities/display.styl
  stylus/utilities/spaces.styl
  stylus/utilities/text.styl
Labels: bug

#530 feat: add cursor utility classes
  stylus/cozy-ui/build.styl
  stylus/utilities/cursor.styl
Labels: enhancement

#532 Chore/clean doc
  react/Chip/index.jsx
  react/Chip/styles.styl
  react/Nav/index.jsx
  react/Nav/styles.styl
  react/__snapshots__/examples.spec.jsx.snap
  stylus/components/button.styl
  stylus/components/nav.styl
  stylus/cozy-ui/build.styl
Labels: documentation

#535 Feat/title classes
  react/Text/index.jsx
  react/Text/styles.styl
  react/__snapshots__/examples.spec.jsx.snap
  stylus/components/list.styl
  stylus/cozy-ui/build.styl
  stylus/generic/typography.styl
Labels: enhancement

#536 feat: add rem() mixin
  react/Hero/styles.styl
  react/IntentHeader/styles.styl
  react/IntentModal/styles.styl
  react/Menu/styles.styl
  react/Modal/styles.styl
  react/SelectBox/styles.styl
  react/Spinner/styles.styl
  react/Toggle/styles.styl
  stylus/components/action-menu.styl
  stylus/components/alerts.styl
  stylus/components/avatar.styl
  stylus/components/badge.styl
  stylus/components/button.styl
  stylus/components/chip.styl
  stylus/components/empty.styl
  stylus/components/forms.styl
  stylus/components/list.styl
  stylus/components/menu.styl
  stylus/components/modals.styl
  stylus/components/nav.styl
  stylus/components/popover.styl
  stylus/components/selectionbar.styl
  stylus/components/table.styl
  stylus/components/tabs.styl
  stylus/elements/defaults.styl
  stylus/generic/typography.styl
  stylus/objects/layouts.styl
  stylus/objects/sidebar.styl
  stylus/settings/breakpoints.styl
  stylus/settings/icons.styl
  stylus/tools/mixins.styl
  stylus/utilities/display.styl
  stylus/utilities/spaces.styl
  stylus/utilities/text.styl
Labels: enhancement

#538 fix: border on table divider
  stylus/components/table.styl
Labels: bug

#540 Exposed initTranslation() and allowed polyglot prop for I18n
  react/I18n/index.jsx
Labels: enhancement

#546 fix: IntentModal Cross position
  react/IntentModal/styles.styl
Labels: bug

#548 Allow emoji as commit message prefix 😂✊🎉
  commitlint.config.js
  package.json
  parser-preset.js
  release.config.js
Labels: enhancement

#550 feat: add layout component
  docs/styleguide.config.js
  react/Layout/Layout.jsx
  react/Layout/Layout.md
  react/Layout/Layout.styl
  react/Layout/index.js
  react/index.js
  stylus/components/action-menu.styl
  stylus/components/selectionbar.styl
  stylus/cozy-ui/build.styl
  stylus/objects/layouts.styl
  stylus/objects/sidebar.styl
Labels: enhancement

#552 fix: bar z-index just over nav z-index
  stylus/settings/z-index.styl
Labels: bug
