Repository cozy/cozy-ui, pull requests merged in 2018-08, with the labels that each got.

#579 fix(Button): Darken secondary subtle button for readability
  stylus/components/button.styl
Labels: bug

#576 fix: layout overflowing on tablet and smaller
  stylus/elements/defaults.styl
Labels: bug

#583 feat: add basic colors for overwriting
  stylus/cozy-ui/build.styl
  stylus/settings/palette.json
Labels: enhancement

#587 fix: Alerts' wrapper doesn't prevent click throught it anymore
  stylus/components/alerts.styl
Labels: bug

#588 fix: Alerts have increased z-index when a Modal is displayed
  react/Alerter/styles.styl
  react/Modal/index.jsx
  stylus/components/alerts.styl
Labels: bug

#592 chore: 📚 Update Text documentation
  react/Accordion/Readme.md
  react/Text/Readme.md
  react/Text/index.jsx
  react/__snapshots__/examples.spec.jsx.snap
  react/index.js
Labels: documentation

#595 feat: ✨ Add Round icon button
  react/Button/Readme.md
  react/Button/index.jsx
  react/Button/styles.styl
  react/__snapshots__/examples.spec.jsx.snap
  stylus/components/button.styl
Labels: enhancement

#596 Add AppIcon component
  assets/icons/ui/icon-cube.svg
  react/AppIcon/Readme.md
  react/AppIcon/index.jsx
  react/AppIcon/styles.styl
  react/AppIcon/test/AppIcon.spec.js
  react/AppIcon/test/__snapshots__/AppIcon.spec.js.snap
Labels: enhancement

#599 Better asynchronous test for AppIcon
  react/AppIcon/test/AppIcon.spec.js
Labels: enhancement
