Repository cozy/cozy-ui, pull requests merged in 2019-04, with the labels that each got.

#880 feat: Add border-radius utility classes
  stylus/cozy-ui/build.styl
  stylus/utilities/border.styl
Labels: enhancement

#893 fix: Remove warning of deprecated typography
  react/MuiCozyTheme/theme.js
Labels: material-ui

#894 Avoid styling form element when `aria-disabled` is `false`
  stylus/components/forms.styl
Labels: enhancement

#949 Field: Inject name prop
  react/Field/Readme.md
  react/Field/index.jsx
  react/SelectBox/SelectBox.jsx
  react/__snapshots__/examples.spec.jsx.snap
Labels: enhancement

#951 fix: Update Spinner default color
  react/Spinner/index.jsx
  react/__snapshots__/examples.spec.jsx.snap
Labels: bug
