Repository cozy/cozy-ui, pull requests merged in 2019-11, with the labels that each got.

#1230 feat(CompositeRow): Spread props
  react/CompositeRow/index.jsx
Labels: released

#1267 Feat/tracker
  react/helpers/tracker.jsx
  react/helpers/tracker.spec.js
Labels: enhancement, merge

#1266 feat: Handle Buttons when upgrading Icons
  codemods/new-icons.js
Labels: bug

#1258 ModalStack
  react/ViewStack/ModalStack.jsx
  react/ViewStack/index.js
Labels: enhancement

#1068 feat: Invert Preact/React flag so that React becomes the default
  react/I18n/index.jsx
  react/Portal/index.jsx
Labels: enhancement
